### ISSUE TITLE
v5.9 panic

### ISSUE THREAD

**Issue by semihalev** [bluesuncorp/validator#85]
Hi All,

I use github.com/gin/gin-gonic web framework, and the framework use your validator and i received panic every request. Here the panic log.

2015/06/28 19:32:07 Panic recovery -> runtime error: index out of range
/usr/local/go/src/runtime/panic.go:387 (0x466f18)
        gopanic: reflectcall(unsafe.Pointer(d.fn), deferArgs(d), uint32(d.siz), uint32(d.siz))
/usr/local/go/src/runtime/panic.go:12 (0x4660ae)
        panicindex: panic(indexError)
/root/go/src/gopkg.in/bluesuncorp/validator.v5/validator.go:369 (0x6dbd16)
/root/go/src/gopkg.in/bluesuncorp/validator.v5/validator.go:333 (0x6da7b2)
/root/go/src/gopkg.in/bluesuncorp/validator.v5/validator.go:324 (0x6da600)

How can i solve the problem?

Thanks.

**Comment by joeybloggs** [comment]
from gin issue: https://github.com/gin-gonic/gin/issues/355

The validator version is latest 5.9.

The code:
```go
type ExternalCMD struct {
    Userid string      `json:"userid"`
    Action uint32      `json:"action"`
    Data   interface{} `json:"data,omitempty"`
}

func kickAction(c *gin.Context) {
    var ecmd ExternalCMD
    c.Bind(&ecmd)

    var user *User
    users.Lock()
    for _, tmpuser := range users.m {
        if tmpuser.mIzmoId == ecmd.Userid {
            user = tmpuser
        }
    }
    users.Unlock()

    if user == nil {
        c.JSON(http.StatusOK, gin.H{"status": "error", "message": "user not found"})
        return
    }

    if ecmd.Action == 10000 {
        user.Disconnect()
    }

    c.JSON(http.StatusOK, gin.H{"status": "ok"})
}

v1.POST("/kick", kickAction)
```
The POST Payload: {"userid":"123456", "action":10000}

**Comment by joeybloggs** [comment]
quick update, it looks like I have a bug handling type interface.

the error stack trace you provided, suggests a different issue, I suspect that the real error was recovered from within gin, and because of that the cache within the validator plugin got out of sync and caused the issues your having now.

I will refactor the code not to store the cached data until all fields have been processed successfully, so the cache cannot get out of sync. and I will address the interface issue within validator.

I should be able to fix this within a day.
