### ISSUE TITLE
using sync.Pool

### ISSUE THREAD

**Issue by manucorporat** [bluesuncorp/validator#98]
This is just a suggestion: so instead of implementing your own pool:
https://github.com/bluesuncorp/validator/blob/v5/validator.go#L47-L52

it could be a good idea to use the built-in pool implementation of the sync package.

**Comment by joeybloggs** [comment]
I will look into it, thanks!

**Comment by joeybloggs** [comment]
it helps with parallel benchmarks a bit and slightly increases the non parallel ones, but it's negligible.

since this library is fully thread safe and I suspect will be used within a webserver or some other logic that will be parallelized this change will help with that.

so going forward with the change.

**Comment by manucorporat** [comment]
Awesome, here another advantage:
- less code -> less possible bugs

:smile:

**Comment by joeybloggs** [comment]
True,

ok v5.10 is now out, I had to drop support for go 1.2 for this change, but I think that's more than justified.

**Comment by manucorporat** [comment]
@joeybloggs yes! I think it is ok to drop support for Go 1.2.
Go 1.4.2 is the most stable version to date and it is the default one in Google App Engine, so...
